---
# defaults file for RandomSecret

annotations: []
labels: []
data: {}
current_keys: []
current_last_rotated_at: {}
random_keys: []
string_data: {}
_data: "{{ data }}"
_last_rotated_at: {}

# compat setup that works for either setting of snakeCaseParameters
default_chars: "{{ defaultChars|default('ascii_letters,digits') }}"
default_length: "{{ defaultLength|default(16) }}"
default_update_seconds: "{{ defaultUpdateSeconds|default(86400) }}"
default_update_strategy: "{{ defaultUpdateStrategy|default('keep') }}"
default_type: "{{ defaultType|default('Opaque') }}"
setup_jobspec: "{{ setupJobspec|default({}) }}"
teardown_jobspec: "{{ teardownJobspec|default({}) }}"
_random_keys: "{{ randomKeys|default(random_keys) }}"
_string_data: "{{ stringData|default(string_data) }}"
