# permissions for end users to edit randomsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: randomsecret-editor-role
rules:
- apiGroups:
  - util.puzzle-itc.de
  resources:
  - randomsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - util.puzzle-itc.de
  resources:
  - randomsecrets/status
  verbs:
  - get
