apiVersion: util.puzzle-itc.de/v1alpha1
kind: RandomSecret
metadata:
  name: randomsecret-sample
spec:
  defaultChars: ascii_letters
  defaultLength: 8
  stringData:
    static_key1: static_value1
    static_key2: static_value2
  labels:
    app: sample
  annotations:
    source: random
  randomKeys:
  - random1
  - random2
  - name: random3
    chars: ascii_letters,digits
    length: 24
    updateSeconds: 60
    updateStrategy: rotate
  setupJobspec:
    template:
      spec:
        containers:
        - name: setup-demo
          image: busybox
          args:
          - /bin/sh
          - "-c"
          - "echo 'Creating external resources using random credentials'; head -n 10 /credentials/*"
          volumeMounts:
          - name: randomsecret-volume
            mountPath: "/credentials"
            readOnly: true
        restartPolicy: Never
        volumes:
        - name: randomsecret-volume
          secret:
            secretName: randomsecret-sample
  teardownJobspec:
    template:
      spec:
        containers:
        - name: teardown-demo
          image: busybox
          args:
          - /bin/sh
          - "-c"
          - "echo 'Removing external resources using random credentials'; head -n 10 /credentials/*"
          volumeMounts:
          - name: randomsecret-volume
            mountPath: "/credentials"
            readOnly: true
        restartPolicy: Never
        volumes:
        - name: randomsecret-volume
          secret:
            secretName: randomsecret-sample
