apiVersion: util.puzzle-itc.de/v1alpha1
kind: RandomSecret
metadata:
  name: randomsecret-sample
spec:
  defaultChars: ascii_letters
  defaultLength: 8
  stringData:
    static_key1: static_value1
    static_key2: static_value2
  labels:
    app: sample
  annotations:
    source: random
  randomKeys:
  - random1
  - random2
  - name: random3
    chars: ascii_letters,digits
    length: 24
